// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SONA.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240806165759_Ottel")]
    partial class Ottel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("GuestId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPaidAtHotel")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<int>("ReservationId2")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("GuestId");

                    b.HasIndex("ReservationId");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuestId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStatus")
                        .HasColumnType("bit");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ReservationId");

                    b.HasIndex("GuestId");

                    b.HasIndex("PaymentId")
                        .IsUnique()
                        .HasFilter("[PaymentId] IS NOT NULL");

                    b.HasIndex("RoomId");

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("SONA.Models.Guest", b =>
                {
                    b.Property<int>("GuestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuestId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStatus")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GuestId");

                    b.ToTable("Guest");
                });

            modelBuilder.Entity("SONA.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int");

                    b.HasKey("RoomId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Room");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "101",
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 2,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "102",
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 3,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "103",
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 4,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "104",
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 5,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "105",
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 6,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "106",
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 7,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "107",
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 8,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "108",
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 9,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "109",
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 10,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "110",
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 11,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "111",
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 12,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "112",
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 13,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "113",
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 14,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "114",
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 15,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "115",
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 16,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "116",
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 17,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "117",
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 18,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "118",
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 19,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "119",
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 20,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "120",
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 21,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "121",
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 22,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "122",
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 23,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "123",
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 24,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "124",
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 25,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "125",
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 26,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "126",
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 27,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "127",
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 28,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "128",
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 29,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "129",
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 30,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "130",
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 31,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "201",
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 32,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "202",
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 33,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "203",
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 34,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "204",
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 35,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "205",
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 36,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "206",
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 37,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "207",
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 38,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "208",
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 39,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "209",
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 40,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "210",
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 41,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "211",
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 42,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "212",
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 43,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "213",
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 44,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "214",
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 45,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "215",
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 46,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "216",
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 47,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "217",
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 48,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "218",
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 49,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "219",
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 50,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "220",
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 51,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "221",
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 52,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "222",
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 53,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "223",
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 54,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "224",
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 55,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "225",
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 56,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "226",
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 57,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "227",
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 58,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "228",
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 59,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "229",
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 60,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "230",
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 61,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "301",
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 62,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "302",
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 63,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "303",
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 64,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "304",
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 65,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "305",
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 66,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "306",
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 67,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "307",
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 68,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "308",
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 69,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "309",
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 70,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "310",
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 71,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "311",
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 72,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "312",
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 73,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "313",
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 74,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "314",
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 75,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "315",
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 76,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "316",
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 77,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "317",
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 78,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "318",
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 79,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "319",
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 80,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "320",
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 81,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "321",
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 82,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "322",
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 83,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "323",
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 84,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "324",
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 85,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "325",
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 86,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "326",
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 87,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "327",
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 88,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "328",
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 89,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "329",
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 90,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "330",
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 91,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "401",
                            RoomTypeId = 4
                        },
                        new
                        {
                            RoomId = 92,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "402",
                            RoomTypeId = 4
                        },
                        new
                        {
                            RoomId = 93,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "403",
                            RoomTypeId = 4
                        },
                        new
                        {
                            RoomId = 94,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "404",
                            RoomTypeId = 4
                        },
                        new
                        {
                            RoomId = 95,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "405",
                            RoomTypeId = 4
                        },
                        new
                        {
                            RoomId = 96,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "406",
                            RoomTypeId = 4
                        },
                        new
                        {
                            RoomId = 97,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "407",
                            RoomTypeId = 4
                        },
                        new
                        {
                            RoomId = 98,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "408",
                            RoomTypeId = 4
                        },
                        new
                        {
                            RoomId = 99,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "409",
                            RoomTypeId = 4
                        },
                        new
                        {
                            RoomId = 100,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "410",
                            RoomTypeId = 4
                        },
                        new
                        {
                            RoomId = 101,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "411",
                            RoomTypeId = 4
                        },
                        new
                        {
                            RoomId = 102,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "412",
                            RoomTypeId = 4
                        },
                        new
                        {
                            RoomId = 103,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "413",
                            RoomTypeId = 4
                        },
                        new
                        {
                            RoomId = 104,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "414",
                            RoomTypeId = 4
                        },
                        new
                        {
                            RoomId = 105,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "415",
                            RoomTypeId = 4
                        },
                        new
                        {
                            RoomId = 106,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "416",
                            RoomTypeId = 4
                        },
                        new
                        {
                            RoomId = 107,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "417",
                            RoomTypeId = 4
                        },
                        new
                        {
                            RoomId = 108,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "418",
                            RoomTypeId = 4
                        },
                        new
                        {
                            RoomId = 109,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "419",
                            RoomTypeId = 4
                        },
                        new
                        {
                            RoomId = 110,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "420",
                            RoomTypeId = 4
                        },
                        new
                        {
                            RoomId = 111,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "421",
                            RoomTypeId = 4
                        },
                        new
                        {
                            RoomId = 112,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "422",
                            RoomTypeId = 4
                        },
                        new
                        {
                            RoomId = 113,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "423",
                            RoomTypeId = 4
                        },
                        new
                        {
                            RoomId = 114,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "424",
                            RoomTypeId = 4
                        },
                        new
                        {
                            RoomId = 115,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "425",
                            RoomTypeId = 4
                        },
                        new
                        {
                            RoomId = 116,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "426",
                            RoomTypeId = 4
                        },
                        new
                        {
                            RoomId = 117,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "427",
                            RoomTypeId = 4
                        },
                        new
                        {
                            RoomId = 118,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "428",
                            RoomTypeId = 4
                        },
                        new
                        {
                            RoomId = 119,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "429",
                            RoomTypeId = 4
                        },
                        new
                        {
                            RoomId = 120,
                            IsAvailable = true,
                            IsDelete = false,
                            RoomNumber = "430",
                            RoomTypeId = 4
                        });
                });

            modelBuilder.Entity("SONA.Models.RoomType", b =>
                {
                    b.Property<int>("RoomTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomTypeId"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("TypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomTypeId");

                    b.ToTable("RoomType");

                    b.HasData(
                        new
                        {
                            RoomTypeId = 1,
                            BasePrice = 100m,
                            Capacity = 1,
                            IsDelete = false,
                            TypeName = "Single"
                        },
                        new
                        {
                            RoomTypeId = 2,
                            BasePrice = 150m,
                            Capacity = 2,
                            IsDelete = false,
                            TypeName = "Double"
                        },
                        new
                        {
                            RoomTypeId = 3,
                            BasePrice = 250m,
                            Capacity = 3,
                            IsDelete = false,
                            TypeName = "Suite"
                        },
                        new
                        {
                            RoomTypeId = 4,
                            BasePrice = 300m,
                            Capacity = 4,
                            IsDelete = false,
                            TypeName = "Family"
                        });
                });

            modelBuilder.Entity("SONA.Models.UserRegistration", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("UserRegistration");
                });

            modelBuilder.Entity("Payment", b =>
                {
                    b.HasOne("SONA.Models.Guest", "Guest")
                        .WithMany()
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Reservation", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Reservation", b =>
                {
                    b.HasOne("SONA.Models.Guest", "Guest")
                        .WithMany("Reservations")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Payment", "Payment")
                        .WithOne()
                        .HasForeignKey("Reservation", "PaymentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SONA.Models.Room", "Room")
                        .WithMany("Reservations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Guest");

                    b.Navigation("Payment");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SONA.Models.Room", b =>
                {
                    b.HasOne("SONA.Models.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("SONA.Models.Guest", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("SONA.Models.Room", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("SONA.Models.RoomType", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
